CREATE TABLE IF NOT EXISTS affiliates (
  id BIGSERIAL PRIMARY KEY,
  nome VARCHAR(160) NOT NULL,
  rede VARCHAR(80) NOT NULL DEFAULT '',
  url TEXT NOT NULL,
  titulo VARCHAR(180) NOT NULL,
  categoria VARCHAR(100) NOT NULL DEFAULT '',
  local VARCHAR(100) NOT NULL DEFAULT 'geral',
  ativo BOOLEAN NOT NULL DEFAULT TRUE,
  prioridade INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS affiliate_clicks (
  id BIGSERIAL PRIMARY KEY,
  affiliate_id BIGINT NOT NULL REFERENCES affiliates(id) ON DELETE CASCADE,
  placement VARCHAR(100) NOT NULL DEFAULT 'geral',
  user_agent TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS admin_sms_codes (
  id BIGSERIAL PRIMARY KEY,
  code_hash VARCHAR(64) NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
